version: '3'

services:
  db:
    container_name: bookstore_db
    image: postgres:13
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend

  web:
    container_name: bookstore_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=bookstore
      - SQL_USER=user
      - SQL_PASSWORD=password
      - SQL_HOST=db
      - SQL_PORT=5432
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SECRET_KEY=sua_secret_key
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    name: bookstore_backend
    driver: bridge